services:
  auth-service:
    build: .
    environment:
      DATABASETYPE: mongo
      MONGO__URL: mongodb://root:root@mongo:27017
    ports:
      - '5095:8080'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
